# Port du serveur web
server.port=8080

# Configuration de la base de données H2 (En mémoire)
spring.datasource.url=jdbc:h2:mem:uno_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Création automatique des tables
spring.jpa.hibernate.ddl-auto=update

# Activer l'interface web pour voir vos données !
spring.h2.console.enabled=true